import pygame
import math

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 600
PLAYING_BOARD_POS = (297, 113)
PLAYING_AREA_WIDTH = SCREEN_WIDTH
CARD_SLOTS = 6

CARD_SLOT_SIZE = (PLAYING_AREA_WIDTH//CARD_SLOTS), (PLAYING_AREA_WIDTH//CARD_SLOTS)*13/10
PIXEL_SIZE = CARD_SLOT_SIZE[0]/10
CARD_PADDING = 2*PIXEL_SIZE
CARD_SIZE = CARD_SLOT_SIZE[0]-2*PIXEL_SIZE, CARD_SLOT_SIZE[1]-3*PIXEL_SIZE
NO_COLOUR = pygame.Color(0, 0, 0, 0)
CARD_POSITIONS = tuple([(i * (CARD_SIZE[0] + CARD_PADDING) + 1.5*PIXEL_SIZE, 1.5*PIXEL_SIZE) for i in range(CARD_SLOTS)])
