import pygame

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 600

PLAYING_AREA_WIDTH = 3 * SCREEN_WIDTH // 5
CARD_SLOTS = 6
CARD_SLOT_SIZE = (PLAYING_AREA_WIDTH//CARD_SLOTS), (PLAYING_AREA_WIDTH//CARD_SLOTS)*14/10
CARD_SLOT_CENTRE = (PLAYING_AREA_WIDTH//CARD_SLOTS)*11/20, (PLAYING_AREA_WIDTH//(CARD_SLOTS))*7/10
PIXEL_SIZE = CARD_SLOT_SIZE[0]/10
CARD_PADDING = 2*PIXEL_SIZE
CARD_SIZE = CARD_SLOT_SIZE[0]-2*PIXEL_SIZE, CARD_SLOT_SIZE[1]-3*PIXEL_SIZE

HAND_CARD_SIZE = CARD_SIZE[0]//2, CARD_SIZE[1]//2
HAND_UI_AREA = (SCREEN_WIDTH * 3 / 5, HAND_CARD_SIZE[1])
HAND_UI_POS = (SCREEN_WIDTH - HAND_UI_AREA[0]) / 2, SCREEN_HEIGHT - HAND_CARD_SIZE[1]

PLAYING_BOARD_POS = (SCREEN_WIDTH//2, HAND_UI_POS[1] - CARD_SLOT_SIZE[1]//2)
CARD_POSITIONS = tuple([(i * (CARD_SIZE[0] + CARD_PADDING) + 1.5*PIXEL_SIZE, 1.5*PIXEL_SIZE) for i in range(CARD_SLOTS)])

NO_COLOUR = pygame.Color(0, 0, 0, 0)

HOLD_WINDOW = 0.15